spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/spring_security_login
      username: root
      password: 123456
kobe:
  security:
    image:
      width: 100
    def:
      loginType: JSON

